test_that("full retrieval records the publisher, query, timing, and integrity outcome", {
  transport <- fixture_transport()
  local_mocked_bindings(arcgis_http = transport$http, .package = "tampaBayOpenData")
  started <- Sys.time()
  result <- get_dataset("construction-permits", fields = c("RECORD_ID", "NEWCONSTRUCTIONSF"),
                         where = "PROJECTSTATUS = 'Issued'", timeout = 9)
  finished <- Sys.time()
  provenance <- dataset_provenance(result)
  entry <- dataset_info("construction-permits")
  expect_identical(provenance$dataset_id, "construction-permits")
  expect_identical(provenance$publisher, "City of Tampa")
  expect_identical(provenance$jurisdiction, "tampa")
  expect_identical(provenance$title, entry$title)
  expect_identical(provenance$source_url, entry$source_url)
  expect_identical(provenance$service_url, entry$service_url)
  expect_identical(provenance$endpoint, paste0(entry$service_url, "/0/query"))
  expect_identical(provenance$terms, entry$terms)
  expect_identical(provenance$endpoint_verified, entry$verified)
  expect_identical(provenance$query$where, "PROJECTSTATUS = 'Issued'")
  expect_identical(provenance$query$fields, c("RECORD_ID", "NEWCONSTRUCTIONSF"))
  expect_false(provenance$query$spatial)
  expect_identical(provenance$query$limit, Inf)
  expect_equal(provenance$matched_rows, nrow(result))
  expect_equal(provenance$returned_rows, nrow(result))
  expect_true(provenance$complete)
  expect_s3_class(provenance$started_at, "POSIXct")
  expect_s3_class(provenance$retrieved_at, "POSIXct")
  expect_true(provenance$started_at >= started)
  expect_true(provenance$retrieved_at <= finished)
  expect_true(provenance$retrieved_at >= provenance$started_at)
  expect_identical(attr(provenance$retrieved_at, "tzone"), "UTC")
  expect_identical(attr(result, "source"), provenance)
  expect_identical(attr(result, "dataset_id"), provenance$dataset_id)
  expect_identical(attr(result, "jurisdiction"), provenance$jurisdiction)
  expect_identical(attr(result, "retrieved_at"), provenance$retrieved_at)
  expect_identical(provenance$field_schema[[2L]]$alias, "Record ID")
  expect_identical(provenance$date_fields_time_reference$timeZoneIANA, "America/New_York")
  expect_null(provenance$spatial_reference)
})

test_that("a caller-selected subset is visibly incomplete when more rows match", {
  transport <- fixture_transport()
  local_mocked_bindings(arcgis_http = transport$http, .package = "tampaBayOpenData")
  result <- get_dataset("construction-permits", limit = 3)
  provenance <- dataset_provenance(result)
  expect_identical(result$OBJECTID, 1:3)
  expect_equal(provenance$matched_rows, 5)
  expect_equal(provenance$returned_rows, 3)
  expect_false(provenance$complete)
  expect_equal(provenance$query$limit, 3)
  expect_length(fixture_queries(transport, "features"), 2L)
  expect_true(dataset_provenance(get_dataset("construction-permits", limit = 10))$complete)
})

test_that("objects without package source attributes explain the missing provenance", {
  expect_error(dataset_provenance(tibble::tibble(id = 1L)), "no tampaBayOpenData")
  expect_error(dataset_provenance(structure(list(), source = "invalid")), "no tampaBayOpenData")
  expect_error(dataset_provenance(structure(list(), source = list(publisher = "someone"))),
               "no tampaBayOpenData")
})
